DATABASE_URL = "sqlite:////tmp/index.db"

CARD_MAX_LENGTH = 100
CARD_MIN_LEVEL = 0
CARD_MAX_LEVEL = 9
CARD_NEXT_DEFAULT = "1970-01-01"

IMAGE_DIR = "/tmp"

QUESTION_RESET_TIME = "05:00:00"

TIME_FORMAT = "%H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"
