DATABASE_URL = "sqlite:////tmp/index.db"

CARD_LEVEL_MIN = 0
CARD_LEVEL_MAX = 9

CARD_LEVEL_ZERO_INTERVAL = 0
CARD_LEVEL_ONE_INTERVAL = 1
CARD_LEVEL_TWO_INTERVAL = 3
CARD_LEVEL_THREE_INTERVAL = 5
CARD_LEVEL_FOUR_INTERVAL = 7
CARD_LEVEL_FIVE_INTERVAL = 15
CARD_LEVEL_SIX_INTERVAL = 30
CARD_LEVEL_SEVEN_INTERVAL = 60
CARD_LEVEL_EIGHT_INTERVAL = 120
CARD_LEVEL_NINE_INTERVAL = 240

CARD_NEXT_DEFAULT = "1970-01-01"

CARD_LENGTH_MAX = 100

IMAGE_DIR = "./index/static/images"

QUESTION_RESET_TIME = "05:00:00"
QUESTION_FRESH_MAX = 10

TIME_FORMAT = "%H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S"

CORS_ORIGINS = "http://localhost:9000"
